// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycuketuvdkuhhlysjaeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljdWtldHV2ZGt1aGhseXNqYWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzE3OTEsImV4cCI6MjA1ODcwNzc5MX0.JD_R70IWMPVp2q7WjtEqBofkrEfsPqyWumqUJNPV7yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);